### ISSUE TITLE
请将文档中的链接地址改成绝对路径, 很多链接在github中无法直接打开, 进行review

### ISSUE THREAD

**Issue by chpaadmin** [wacn/aog-content#10]
文档: virtual-machines-troubleshoot-ssh-connections.md 
请将文档中的链接地址改成绝对路径, 很多链接在github中无法直接打开, 进行review
其他文档估计也有类似的问题.

**Comment by jierong** [comment]
Hi chpaadmin,

谢谢提建议，但是文档中的链接我们都是用相对路径的，因为部分文档（文件名不是以aog-开头的）是来自A.CN的技术文档，这些文档又是来自A.COM的技术文档定制和翻译的，里面都是用相对路径的，这样又保证MD ENGINE在REDNER这些MD文件里自动加上HOST，如果想看链接中的内容的话，建议可以在文件名前加上下面的前缀，这样会进入A.CN的REPO去REVIEW那文章。比如要REVIEW XXX.MD这文章，就用下面的这个URL就行了。

https://github.com/wacn/techcontent/blob/master/articles/XXXX.md

Thanks,
Jie
