### ISSUE TITLE
wrong article link

### ISSUE THREAD

**Issue by Bobbiez** [wacn/aog-content#16]
在aog-content里这篇文章对应的名字为“对 Windows Azure 虚拟机的远程桌面连接进行基本故障排除”，与实际不符。

**Comment by jierong** [comment]
谢谢指出问题，希望在提出问题的时候可以引用文件名，这样方便我们定位，因为Issues是针对REPO的。

我们已经在 

https://www.azure.cn/documentation/services/azure-operations-guide/
和
https://www.azure.cn/documentation/articles/virtual-machines-windows-troubleshoot-rdp-connection/

上面修复。
