### ISSUE TITLE
使用Azure Java SDK创建VM

### ISSUE THREAD

**Issue by xingzhougmu** [wacn/aog-content#17]
1. Azure SDK提供多种认证方式，以下主要提供两种认证方式，publishsetting 和 证书
**改成：**Azure SDK提供多种认证方式，以下主要提供两种认证方式，publishsetting**文件认证** 和 证书**认证**。

2. 1.Publishsettings文件认证 这里提到了证书的下载链接。Publishsettings 文件有两个version，请作者确认下提供的示例代码是否对两个version都适用？

3. **创建系统磁盘和数据磁盘** 这一节，“但创建时，必须指定VHD文件的位置“后面少个句号。

**Comment by JamborYao** [comment]
>>Publishsettings 文件有两个version
我们可以通过链接https://manage.windowsazure.cn/publishsettings或者Get-AzurePublishSettingsFile来得到publishsettings文件，这里提到的两个版本具体指的是什么，有什么方式可以得到不同版本的publishsettings文件？还希望给我些帮助，我将进一步测试是否都适用。

**Comment by xingzhougmu** [comment]
Publishsettings 有两种版本  SchemaVersion=1.0 ,  2.0

  1.  是 ./PublishProfile/ ManagementCertificate 结构的
可以从以下地址下载： https://manage.windowsazure.cn/publishsettings/index?client=eclipse&SchemaVersion=1.0<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fmanage.windowsazure.cn%2fpublishsettings%2findex%3fclient%3declipse%26SchemaVersion%3d1.0&data=01%7c01%7callenl%40064d.mgd.microsoft.com%7c9006c2f0709a444f5ce308d3b140be27%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=woaPnvklsv%2bQy9KUqMj9SiL7GEnj2zM13mA0WolY0rY%3d>


  1.  就是现在常用的版本，其结构是./PublishProfile/Subscription/ ManagementCertificate
可以通过以下地址下载：https://manage.windowsazure.cn/publishsettings/index<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fmanage.windowsazure.cn%2fpublishsettings%2findex&data=01%7c01%7callenl%40064d.mgd.microsoft.com%7c9006c2f0709a444f5ce308d3b140be27%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=CZx4hsDtdwkQTc%2fIKQBcTyMiaqIB56uaAyRyUPDzWp8%3d>


Best Regards | Shing (Xing) Zhou

[cid:image001.png@01D05A96.17894250]

**Comment by JamborYao** [comment]
>2

我分别下载publishsettings去做测试，结果是两个版本的publishsettings文件都是能正确工作的。

**Comment by jierong** [comment]
Hi Shing, do you have any other commets? If no, please provide sign-off, and we will close this Issue and publish the content to 常用操作指南.

**Comment by xingzhougmu** [comment]
@jierong yes. It's ready to go!
